services:
  sqlserver:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: SqlServer-FabiaNatura
    hostname: SqlServer-FabiaNatura
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Admin123!"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
      - C:/FabiaNaturaBD:/FabiaNaturaBD
    networks:
      - sqlserver_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "sqlcmd -S localhost -U sa -P Admin123! -Q 'SELECT 1' || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

volumes:
  sqlserver_data:
    driver: local

networks:
  sqlserver_network:
    driver: bridge
